apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-dev-volume1
  labels:
    name: mysql1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "v01"
    readOnly: false
