apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-mysql1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: "mysql1"
