apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity
spec:
  affinity:
    podAffinity:
      requireDuringSchedulingIgnoreDuringExecution:
      - labelSelector:
         matchExpressions:
         - key: security
           operation: In
           values:
           - S1
      topologyKey: failure-domain.beta.kubernetes.io/zone
    podAntiAffinity:
      requireDuringSchedulingIgnoreDuringExecution:
      - labelSelector:
         matchExpressions:
         - key: app
           operation: In
           values:
           - nginx
      topologyKey: kubernetes.io/hostname 
