apiVersion: v1
kind: Pod
metadata:
  name: liveness-httpget
spec:
 containers:
 - name: nginx
   image: nginx
   ports:
   - containerPort: 80
   livenessProbe:
     httpGet:
       path: /_status/healthz
       port: 80
     initialDelaySeconds: 30
     timeoutSeconds: 15
