apiVersion: v1
kind: Pod
metadata:
  name: job-wq-1
spec:
  containers:
  - name: c
    image: registry.cn-hangzhou.aliyuncs.com/barnettxxf/job-wq-1:latest
    env:
    - name: BROKER_URL
      value: amqp://guest:guest@rabbitmq-service:5672
    - name: QUEUE
      value: job1
  restartPolicy: Never
